### ISSUE TITLE
proof validation failed, sector not found in sector set after cron

### ISSUE THREAD

**Issue by Mercur1A1** [filecash/lotus#1]
lotus-miner has this problem

**Describe the problem:**
```
proof validation failed, sector not found in sector set after cron
```

**Comment by 1825403978** [comment]
If you have this problem you can try:
lotus-miner sectors update-state --really-do-it \<sector\> FinalizeSector
Let the miner fetch sectors from workers, and restart the miner.
Now they should be proving and active

**Comment by rectinajh** [comment]
I.   save wallet
II.  clean lotus data
III. resync lotus

**Comment by Taro945** [comment]
I.   backup wallet
II.  clean lotus data
III. resync lotus

**Comment by hawkinggg** [comment]
> I. backup wallet
> II. clean lotus data
> III. resync lotus

Do I have to delete the .lotus folder and resync lotus to solve this problem?

**Comment by ytQiao** [comment]
I tried it, but it didn't work
My sector is in the `proving` state, but the computing power does not increase, and "proving deadlines" is not displayed

**Comment by ytjoe** [comment]
I tried it, but it didn't work
My sector is in the proving state, but the computing power does not increase, and `proving deadlines` is not displayed

**Comment by hhdllhflower** [comment]
修改后重启lotus-miner，Proving        sSet: NO  active: NO  tktH: 13627 seedH: 15113 deals: [0]  toUpgrade:false
无效的，请问后续怎么操作

**Comment by 1825403978** [comment]
> 修改后重启lotus-miner，Proving sSet: NO active: NO tktH: 13627 seedH: 15113 deals: [0] toUpgrade:false
> 无效的，请问后续怎么操作

under repair, try again later

**Comment by wonderfic** [comment]
It has been resolved
