### ISSUE TITLE
Cluster scheduling and maximum number of tasks

### ISSUE THREAD

**Issue by ytjoe** [filecash/lotus#3]
1. Cluster scheduling problem: I made a cluster of two machines, the miner machine executed all the processes, the worker machine executed precommit2 and commit, and there were tasks waiting in the queue, but the miner did not assign the task to the worker

2. Maximum number of tasks: modify the maximum number of tasks in the miner, but the currently executed tasks still exceed the maximum number of tasks

### lotus version
```Daemon:  0.7.0+git.1fdc7a03.dirty+api0.14.0
Local: lotus version 0.7.0+git.1fdc7a03.dirty```

**Comment by wonderfic** [comment]
It has been resolved
