### ISSUE TITLE
PreCommitFailed  -- SysErrInsufficientFunds

### ISSUE THREAD

**Issue by hawkinggg** [filecash/lotus#4]
lotus-miner sectors status --log 47

> 25.     2020-10-23 11:15:07 +0800 CST:  [event;sealing.SectorRetryPreCommit]    {"User":{}}
> 26.     2020-10-23 11:15:07 +0800 CST:  [event;sealing.SectorChainPreCommitFailed]      {"User":{}}
        pushing message to mpool: GasEstimateMessageGas error: estimating gas used: message execution failed: exit SysErrInsufficientFunds(6), reason: failed to transfer funds (RetCode=6): transfer failed when deducting funds (8451.478092451125247672 FIC): not enough funds (RetCode=6)
> 27.     2020-10-23 11:16:07 +0800 CST:  [event;sealing.SectorRetryPreCommit]    {"User":{}}
> 28.     2020-10-23 11:16:07 +0800 CST:  [event;sealing.SectorChainPreCommitFailed]      {"User":{}}
        pushing message to mpool: GasEstimateMessageGas error: estimating gas used: message execution failed: exit SysErrInsufficientFunds(6), reason: failed to transfer funds (RetCode=6): transfer failed when deducting funds (8417.438546521829068807 FIC): not enough funds (RetCode=6)

lotus-miner sectors list
> 47: PreCommitFailed sSet: NO  active: NO  tktH: 20399 seedH: 0     deals: [0]  toUpgrade:false

miner log

> 2020-10-23T11:04:07.645+0800    ^[[35mDEBUG^[[0m        advmgr  sector-storage/sched.go:573     task done       {"workerid": 3}
> 2020-10-23T11:04:07.663+0800    ^[[34mINFO^[[0m sectors storage-sealing/states_sealing.go:212   submitting precommit for sector 47 (deposit: 8844276429110238534600):
> 2020-10-23T11:04:07.665+0800    ^[[33mWARN^[[0m sectors storage-sealing/fsm.go:469      sector 47 got error event sealing.SectorChainPreCommitFailed: pushing message to mpool: GasEstimateMessageGas error: estimating gas used: message execution failed: exit SysErrInsufficientFunds(6), reason: failed to transfer funds (RetCode=6): transfer failed when deducting funds (8844.2764291102385346 FIC): not enough funds (RetCode=6)
> 2020-10-23T11:04:07.674+0800    ^[[34mINFO^[[0m sectors storage-sealing/states_failed.go:25     PreCommitFailed(47), waiting 59.325125378s before retrying

need 8844 FIC.......

**Comment by jerry-sl** [comment]
Some issue

**Comment by wonderfic** [comment]
It has been resolved
