### ISSUE TITLE
PreCommitFailed

### ISSUE THREAD

**Issue by hhdllhflower** [filecash/lotus#5]
./lotus-miner sectors status 35 --log
SectorID:	35
Status:		PreCommitFailed
CIDcommD:	baga6ea4seaqgntqfunthkuwpixacxtcoqojjdg66vq254l7vmjyyjdu7pntvcby
CIDcommR:	bagboea4b5abcbybaehnqv3jrcfdfaiqob667cuk5rtd7m6ormzdr7seo45dkwxiv
Ticket:		6a1764ea698eeea0ee367bd3000afaf1c3fdb898e0bcb333451a8fb2d03140c7
TicketH:	23649
Seed:		
SeedH:		0
Precommit:	<nil>
Commit:		<nil>
Proof:		
Deals:		[0]
Retries:	0

./lotus-miner sealing workers --color true
Worker 0, host sandy-x299
	CPU:  [                                                                ] 0 core(s) in use
	RAM:  [||                                                              ] 3% 4.544 GiB/125.5 GiB
	VMEM: [                                                                ] 1% 4.544 GiB/381.5 GiB
	GPU: GeForce RTX 2070, not used
	GPU: GeForce RTX 2070, not used
	GPU: GeForce RTX 2070, not used
	GPU: GeForce RTX 2070, not used
	AcceptTasks: [AddPiece Commit1 Commit2 Fetch Finalize PreCommit1 PreCommit2 Unseal Unsealed]
	PreCommit1Max: 0	PreCommit2Max: 0	CommitMax: 0
	PreCommit1Now: 0	PreCommit2Now: 0	CommitNow: 0

**Comment by 1825403978** [comment]
I used the latest version and there is no such problem

**Comment by wonderfic** [comment]
It has been resolved
