### ISSUE TITLE
 Multiple sectors looping between PC1->PC2->PC1 in ticket expired

### ISSUE THREAD

**Issue by hhdllhflower** [filecash/lotus#7]
lotus-miner sectors list
121: PreCommit2          sSet: NO  active: NO  tktH: 8516  seedH: 18703 deals: [0]  toUpgrade:false
---------------------------------------------------
lotus-miner sectors status --log 121
40.	2020-11-06 00:13:51 +0800 CST:	[event;sealing.SectorSealPreCommit1Failed]	{"User":{}}
	ticket expired: ticket expired: seal height: 9416, head: 21937
41.	2020-11-06 00:14:51 +0800 CST:	[event;sealing.SectorRetrySealPreCommit1]	{"User":{}}
42.	2020-11-06 05:59:53 +0800 CST:	[event;sealing.SectorPreCommit1]	{"User":{"PreCommit1Out":"eyJyZWdpc3RlcmVkX3Byb29mIjoiU3RhY2tlZERyZzRHaUJWMSIsImxhYmVscyI6eyJTdGFja2VkRHJnNEdpQlYxIjp7ImxhYmVscyI6W3sicGF0aCI6Ii9kYXRhL2xvdHVzbWluZXIvY2FjaGUvcy10MDEwMzktMTIxIiwiaWQiOiJsYXllci0xIiwic2l6ZSI6MTM0MjE3NzI4LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii9kYXRhL2xvdHVzbWluZXIvY2FjaGUvcy10MDEwMzktMTIxIiwiaWQiOiJsYXllci0yIiwic2l6ZSI6MTM0MjE3NzI4LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii9kYXRhL2xvdHVzbWluZXIvY2FjaGUvcy10MDEwMzktMTIxIiwiaWQiOiJsYXllci0zIiwic2l6ZSI6MTM0MjE3NzI4LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii9kYXRhL2xvdHVzbWluZXIvY2FjaGUvcy10MDEwMzktMTIxIiwiaWQiOiJsYXllci00Iiwic2l6ZSI6MTM0MjE3NzI4LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii9kYXRhL2xvdHVzbWluZXIvY2FjaGUvcy10MDEwMzktMTIxIiwiaWQiOiJsYXllci01Iiwic2l6ZSI6MTM0MjE3NzI4LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii9kYXRhL2xvdHVzbWluZXIvY2FjaGUvcy10MDEwMzktMTIxIiwiaWQiOiJsYXllci02Iiwic2l6ZSI6MTM0MjE3NzI4LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii9kYXRhL2xvdHVzbWluZXIvY2FjaGUvcy10MDEwMzktMTIxIiwiaWQiOiJsYXllci03Iiwic2l6ZSI6MTM0MjE3NzI4LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii9kYXRhL2xvdHVzbWluZXIvY2FjaGUvcy10MDEwMzktMTIxIiwiaWQiOiJsYXllci04Iiwic2l6ZSI6MTM0MjE3NzI4LCJyb3dzX3RvX2Rpc2NhcmQiOjd9XSwiX2giOm51bGx9fSwiY29uZmlnIjp7InBhdGgiOiIvZGF0YS9sb3R1c21pbmVyL2NhY2hlL3MtdDAxMDM5LTEyMSIsImlkIjoidHJlZS1kIiwic2l6ZSI6MjY4NDM1NDU1LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LCJjb21tX2QiOlsxMDIsMjA2LDUsMTYzLDEwMiwxMTcsODIsMjA3LDY5LDE5Miw0MywyMDQsNzgsMTMxLDE0NiwxNDUsMTU1LDIyMiwxNzIsNTMsMjIyLDQ3LDI0NSw5OCwxMTMsMTMyLDE0MiwxNTksMTIzLDEwMyw4MSw3XX0=","TicketValue":"NvIJOEETT1kQkC5iaxwJeo4sJPepth+1hd5fC2dKEcE=","TicketEpoch":8516}}
43.	2020-11-06 07:37:24 +0800 CST:	[event;sealing.SectorPreCommit2]	{"User":{"Sealed":{"/":"bagboea4b5abcbjud2god37ycgcs5m2hl4r6tmso5uikwh4vivj47qur62cqnafzw"},"Unsealed":{"/":"baga6ea4seaqgntqfunthkuwpixacxtcoqojjdg66vq254l7vmjyyjdu7pntvcby"}}}
44.	2020-11-06 07:37:24 +0800 CST:	[event;sealing.SectorSealPreCommit1Failed]	{"User":{}}
	ticket expired: ticket expired: seal height: 9416, head: 22824
45.	2020-11-06 07:38:24 +0800 CST:	[event;sealing.SectorRetrySealPreCommit1]	{"User":{}}
46.	2020-11-06 10:20:28 +0800 CST:	[event;sealing.SectorPreCommit1]	{"User":{"PreCommit1Out":"eyJyZWdpc3RlcmVkX3Byb29mIjoiU3RhY2tlZERyZzRHaUJWMSIsImxhYmVscyI6eyJTdGFja2VkRHJnNEdpQlYxIjp7ImxhYmVscyI6W3sicGF0aCI6Ii9kYXRhL2xvdHVzLXNlYWwvU2VhbDAxL2NhY2hlL3MtdDAxMDM5LTEyMSIsImlkIjoibGF5ZXItMSIsInNpemUiOjEzNDIxNzcyOCwicm93c190b19kaXNjYXJkIjo3fSx7InBhdGgiOiIvZGF0YS9sb3R1cy1zZWFsL1NlYWwwMS9jYWNoZS9zLXQwMTAzOS0xMjEiLCJpZCI6ImxheWVyLTIiLCJzaXplIjoxMzQyMTc3MjgsInJvd3NfdG9fZGlzY2FyZCI6N30seyJwYXRoIjoiL2RhdGEvbG90dXMtc2VhbC9TZWFsMDEvY2FjaGUvcy10MDEwMzktMTIxIiwiaWQiOiJsYXllci0zIiwic2l6ZSI6MTM0MjE3NzI4LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii9kYXRhL2xvdHVzLXNlYWwvU2VhbDAxL2NhY2hlL3MtdDAxMDM5LTEyMSIsImlkIjoibGF5ZXItNCIsInNpemUiOjEzNDIxNzcyOCwicm93c190b19kaXNjYXJkIjo3fSx7InBhdGgiOiIvZGF0YS9sb3R1cy1zZWFsL1NlYWwwMS9jYWNoZS9zLXQwMTAzOS0xMjEiLCJpZCI6ImxheWVyLTUiLCJzaXplIjoxMzQyMTc3MjgsInJvd3NfdG9fZGlzY2FyZCI6N30seyJwYXRoIjoiL2RhdGEvbG90dXMtc2VhbC9TZWFsMDEvY2FjaGUvcy10MDEwMzktMTIxIiwiaWQiOiJsYXllci02Iiwic2l6ZSI6MTM0MjE3NzI4LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii9kYXRhL2xvdHVzLXNlYWwvU2VhbDAxL2NhY2hlL3MtdDAxMDM5LTEyMSIsImlkIjoibGF5ZXItNyIsInNpemUiOjEzNDIxNzcyOCwicm93c190b19kaXNjYXJkIjo3fSx7InBhdGgiOiIvZGF0YS9sb3R1cy1zZWFsL1NlYWwwMS9jYWNoZS9zLXQwMTAzOS0xMjEiLCJpZCI6ImxheWVyLTgiLCJzaXplIjoxMzQyMTc3MjgsInJvd3NfdG9fZGlzY2FyZCI6N31dLCJfaCI6bnVsbH19LCJjb25maWciOnsicGF0aCI6Ii9kYXRhL2xvdHVzLXNlYWwvU2VhbDAxL2NhY2hlL3MtdDAxMDM5LTEyMSIsImlkIjoidHJlZS1kIiwic2l6ZSI6MjY4NDM1NDU1LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LCJjb21tX2QiOlsxMDIsMjA2LDUsMTYzLDEwMiwxMTcsODIsMjA3LDY5LDE5Miw0MywyMDQsNzgsMTMxLDE0NiwxNDUsMTU1LDIyMiwxNzIsNTMsMjIyLDQ3LDI0NSw5OCwxMTMsMTMyLDE0MiwxNTksMTIzLDEwMyw4MSw3XX0=","TicketValue":"NvIJOEETT1kQkC5iaxwJeo4sJPepth+1hd5fC2dKEcE=","TicketEpoch":8516}}
47.	2020-11-06 11:38:31 +0800 CST:	[event;sealing.SectorPreCommit2]	{"User":{"Sealed":{"/":"bagboea4b5abcbjud2god37ycgcs5m2hl4r6tmso5uikwh4vivj47qur62cqnafzw"},"Unsealed":{"/":"baga6ea4seaqgntqfunthkuwpixacxtcoqojjdg66vq254l7vmjyyjdu7pntvcby"}}}
48.	2020-11-06 11:38:31 +0800 CST:	[event;sealing.SectorSealPreCommit1Failed]	{"User":{}}
	ticket expired: ticket expired: seal height: 9416, head: 23306
49.	2020-11-06 11:39:31 +0800 CST:	[event;sealing.SectorRetrySealPreCommit1]	{"User":{}}
50.	2020-11-06 14:41:14 +0800 CST:	[event;sealing.SectorPreCommit1]	{"User":{"PreCommit1Out":"eyJyZWdpc3RlcmVkX3Byb29mIjoiU3RhY2tlZERyZzRHaUJWMSIsImxhYmVscyI6eyJTdGFja2VkRHJnNEdpQlYxIjp7ImxhYmVscyI6W3sicGF0aCI6Ii9kYXRhL2xvdHVzbWluZXIvY2FjaGUvcy10MDEwMzktMTIxIiwiaWQiOiJsYXllci0xIiwic2l6ZSI6MTM0MjE3NzI4LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii9kYXRhL2xvdHVzbWluZXIvY2FjaGUvcy10MDEwMzktMTIxIiwiaWQiOiJsYXllci0yIiwic2l6ZSI6MTM0MjE3NzI4LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii9kYXRhL2xvdHVzbWluZXIvY2FjaGUvcy10MDEwMzktMTIxIiwiaWQiOiJsYXllci0zIiwic2l6ZSI6MTM0MjE3NzI4LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii9kYXRhL2xvdHVzbWluZXIvY2FjaGUvcy10MDEwMzktMTIxIiwiaWQiOiJsYXllci00Iiwic2l6ZSI6MTM0MjE3NzI4LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii9kYXRhL2xvdHVzbWluZXIvY2FjaGUvcy10MDEwMzktMTIxIiwiaWQiOiJsYXllci01Iiwic2l6ZSI6MTM0MjE3NzI4LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii9kYXRhL2xvdHVzbWluZXIvY2FjaGUvcy10MDEwMzktMTIxIiwiaWQiOiJsYXllci02Iiwic2l6ZSI6MTM0MjE3NzI4LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii9kYXRhL2xvdHVzbWluZXIvY2FjaGUvcy10MDEwMzktMTIxIiwiaWQiOiJsYXllci03Iiwic2l6ZSI6MTM0MjE3NzI4LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii9kYXRhL2xvdHVzbWluZXIvY2FjaGUvcy10MDEwMzktMTIxIiwiaWQiOiJsYXllci04Iiwic2l6ZSI6MTM0MjE3NzI4LCJyb3dzX3RvX2Rpc2NhcmQiOjd9XSwiX2giOm51bGx9fSwiY29uZmlnIjp7InBhdGgiOiIvZGF0YS9sb3R1c21pbmVyL2NhY2hlL3MtdDAxMDM5LTEyMSIsImlkIjoidHJlZS1kIiwic2l6ZSI6MjY4NDM1NDU1LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LCJjb21tX2QiOlsxMDIsMjA2LDUsMTYzLDEwMiwxMTcsODIsMjA3LDY5LDE5Miw0MywyMDQsNzgsMTMxLDE0NiwxNDUsMTU1LDIyMiwxNzIsNTMsMjIyLDQ3LDI0NSw5OCwxMTMsMTMyLDE0MiwxNTksMTIzLDEwMyw4MSw3XX0=","TicketValue":"NvIJOEETT1kQkC5iaxwJeo4sJPepth+1hd5fC2dKEcE=","TicketEpoch":8516}}

same issue ,https://github.com/filecoin-project/lotus/issues/4372

**Comment by 1825403978** [comment]
lotus-miner sectors remove --really-do-it <sector>

**Comment by wonderfic** [comment]
It has been resolved
